displayName=Hide Scrying Orb
author=Coopermor
description=Hides the orb when using the scrying pool.
tags=scrying,scry,orb,pool
version=1.0.0
plugins=com.coopermor.hidescryingorb.HideScryingOrbPlugin
build=standard